### ISSUE TITLE
Maybe mention --no-check for faster iterations

### ISSUE THREAD

**Issue by sigmaSd** [c4spar/deno-dzx#17]
dzx type-checks the file each time its run

I personally install it as two separate binaries:
- `deno install --allow-all --unstable -f -n dzxs https://deno.land/x/dzx@0.3.0/dzx.ts #dzx(safe)`
- `deno install --no-check --allow-all --unstable -f https://deno.land/x/dzx@0.3.0/dzx.ts #I prefer to default to the fast version`

I thought this might be worth mentioning somewhere since it makes the experience smoother.

**Comment by c4spar** [comment]
I think this is not necessary since type checking will be disable by default in the future.
https://deno.com/blog/v1.21#deno-check-and-the-path-to-not-type-checking-by-default

**Comment by sigmaSd** [comment]
I agree and I'm already using the new env variable and the experience is better
