### ISSUE TITLE
Deno exit is not needed

### ISSUE THREAD

**Issue by sigmaSd** [c4spar/deno-dzx#21]
I'm not sure whats the usefulness of https://github.com/c4spar/deno-dzx/blob/main/src/_utils.ts#L10

But for the disadvantages, using dzx in the repl, and using for example cd with a directory that does not exist make the whole repl exit which seems excessive

My suggestion is just  to remove it, the caller can just throw to exit the program early, and the repl does catch throws gracefully.

**Comment by c4spar** [comment]
For now i just enabled the `throwErrors` option by default for the repl command in #21.
Maybe i will remove the `throwErrors` options in the next minor version.

**Comment by sigmaSd** [comment]
I think that's enough as long as it doens't make the repl exit
