### ISSUE TITLE
compiled scripts to not include the `$.args` array values

### ISSUE THREAD

**Issue by andrewbrey** [c4spar/deno-dzx#6]
Due to the fact that compilation uses the existing `preBundle` logic found in `dzx bundle`, the results of compiling a script into a standalone binary do not populate the `$.args` array. Is this already working as designed or should the compiled binary include the "script args" passed to the compilation process as the value of `$.args`?

Note that this item was identified while working on #5

**Comment by c4spar** [comment]
it's a bug. i think we can just do `$.args = Deno.args` for the compiled binary and also for the bundle, because the compiled binary and the standalone bundle does not have the script name as the first argument.

**Comment by c4spar** [comment]
ah right maybe we need to do `$.args = [...scriptArgs, ...Deno.args]`

**Comment by andrewbrey** [comment]
Ya, like you noted, it's possibly slightly more complicated than just merging together the various args arrays since that could lead to duplicates...which may or may not matter honestly - this is true for any `deno compile` binary, not just these, and it's a hazard of permitting the "partial embedding" of script arguments. Should it just fall into the "user beware" category and be called "working as designed"? Should we bake into the binary _just_ the script args as passed to `dzx compile`? Or should we try and do something more complicated...IMO, it's your call entirely and any of these options could be called "correct"

**Comment by c4spar** [comment]
i tried it and it seems to work.
If I compile the following script:
```ts
#!/usr/bin/env dzx
/// <reference path="./types.d.ts" />

console.log("args:", Deno.args);
```
with:
```console
$ dzx compile -A ./example.ts -p 80
```
and call it with:
```console
$ ./example --foo bar
args: [ "-p", "80", "--foo", "bar" ]
```
`Deno.args` will contain all arguments. So i think it should be enough to do `$.args = Deno.args`;

**Comment by andrewbrey** [comment]
That is great, it seems to work perfectly - just submitted a PR for this :+1:
